# Generated by Django 4.0.2 on 2022-02-08 03:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0008_alter_paper_exams_alter_paper_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('last_login', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('school', models.CharField(choices=[('Admiralty_Secondary_School', 'Admiralty Secondary School'), ('Anglican_High_School', 'Anglican High School')], max_length=100)),
                ('subject', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Science_(Physics)', 'Science (Physics)'), ('Science_(Chemistry)', 'Science (Chemistry)'), ('Science_(Biology)', 'Science (Biology)'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=100), size=None)),
                ('exams', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Normal_(Academic)', 'Normal (Academic)'), ('Normal_(Technical)', 'Normal (Technical)'), ('Express', 'Express')], max_length=100), size=None)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('results', models.FloatField(default=0)),
                ('duration', models.DurationField(default=0)),
                ('reviewed', models.BooleanField(default=False)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papers.paper')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.student')),
            ],
        ),
    ]
