# Generated by Django 4.0.2 on 2022-02-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
