# Generated by Django 4.0.2 on 2022-02-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaper',
            name='duration',
            field=models.DurationField(default='0'),
        ),
    ]
