# Generated by Django 4.0.2 on 2022-02-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_paper_exams'),
        ('students', '0003_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('results', models.FloatField(default=0)),
                ('duration', models.DurationField(default=0)),
                ('reviewed', models.BooleanField(default=False)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.paper')),
                ('student_username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
        ),
    ]
