# Generated by Django 4.0.2 on 2022-02-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentpaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpaper',
            old_name='student_username',
            new_name='username',
        ),
    ]
