# Generated by Django 4.0.2 on 2022-02-08 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentpaper_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaper',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
