# Generated by Django 4.0.2 on 2022-02-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentpaper_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCompletedPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('paper_id', models.CharField(max_length=255)),
                ('question_number', models.IntegerField()),
                ('question_img', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('student_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('accuracy', models.BooleanField()),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
    ]
