# Generated by Django 4.0.2 on 2022-02-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_alter_question_paper_id'),
        ('students', '0005_alter_studentpaper_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCompletedPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_img', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('student_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('accuracy', models.BooleanField()),
                ('solution', models.CharField(max_length=255)),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='papers.question')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.student')),
            ],
        ),
    ]
