# Generated by Django 4.0.2 on 2022-02-08 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_paper_exams'),
        ('students', '0006_alter_student_contact_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaper',
            name='paper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.paper'),
        ),
        migrations.AlterField(
            model_name='studentpaper',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
