# Generated by Django 4.0.2 on 2022-02-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('subject', models.CharField(choices=[('SP', 'Science (Physics)'), ('SC', 'Science (Chemistry)'), ('SB', 'Science (Biology)'), ('P', 'Physics'), ('C', 'Chemistry'), ('B', 'Biology')], max_length=100)),
                ('exams', models.CharField(choices=[('N', 'Normal (Academic)'), ('T', 'Normal (Technical)'), ('E', 'Express')], max_length=1)),
                ('paper_id', models.CharField(max_length=7)),
                ('subject_code', models.CharField(max_length=4)),
                ('question_number', models.IntegerField()),
                ('question', models.TextField()),
                ('question_img', models.FileField(blank=True, upload_to='')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('solution', models.FileField(upload_to='')),
            ],
        ),
    ]
