# Generated by Django 4.0.2 on 2022-02-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='question',
        ),
        migrations.AlterField(
            model_name='paper',
            name='question_img',
            field=models.FileField(upload_to=''),
        ),
    ]
