# Generated by Django 4.0.2 on 2022-02-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_remove_paper_question_alter_paper_question_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='question_img',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='solution',
            field=models.CharField(max_length=255),
        ),
    ]
