# Generated by Django 4.0.2 on 2022-02-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_alter_paper_exams_alter_paper_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=7)),
                ('question_number', models.IntegerField()),
                ('question_img', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='question_img',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='subject_code',
        ),
    ]
