# Generated by Django 4.0.2 on 2022-02-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_remove_paper_id_alter_paper_paper_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='exams',
            field=models.CharField(choices=[('Normal (Academic)', 'Normal (Academic)'), ('Normal (Technical)', 'Normal (Technical)'), ('Express', 'Express')], max_length=100),
        ),
    ]
