# Generated by Django 4.0.2 on 2022-02-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_paper_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='exams',
            field=models.CharField(choices=[('Normal_(Academic)', 'Normal (Academic)'), ('Normal_(Technical)', 'Normal (Technical)'), ('Express', 'Express')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='subject',
            field=models.CharField(choices=[('Science_(Physics)', 'Science (Physics)'), ('Science_(Chemistry)', 'Science (Chemistry)'), ('Science_(Biology)', 'Science (Biology)'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=100),
        ),
    ]
