# Generated by Django 4.0.2 on 2022-02-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_alter_paper_exams_alter_paper_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='paper_id',
            field=models.CharField(max_length=255),
        ),
    ]
