# Generated by Django 4.0.2 on 2022-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
