# Generated by Django 4.0.2 on 2022-02-07 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_tutor_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subject',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=100), size=None),
        ),
    ]
