# Generated by Django 4.0.2 on 2022-02-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_alter_tutor_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='school',
            field=models.CharField(choices=[('Admiralty_Secondary_School', 'Admiralty Secondary School'), ('Anglican_High_School', 'Anglican High School')], max_length=100),
        ),
    ]
